## Numbeo Extract

To extract from the API of NUmbeo follow the next steps:
- Access the url prefix with a request method e.g. `https://www.numbeo.com:8008/api/<DOCUMENT>?api_key=<YOUR_KEY>`
- Every document (table) in Numbeo has different parameters to query, for more info go to [API doc](https://www.numbeo.com/api/doc.jsp)

In [2]:
import pandas as pd
import requests
import json
from pandas.io.json import json_normalize

In [7]:
#IF YOU WANT TO PRINT
#request = requests.get("http://www.numbeo.com:8008/api/cities?api_key=<YOUR_KEY>")
#json_parse = json.loads(request.text)
#for line in json_parse['cities']:
#    print (line)

In [4]:
#PARSE IN PANDAS
request = requests.get('http://www.numbeo.com:8008/api/cities?api_key=<YOUR_KEY>')

In [5]:
df_cities = json_normalize(json.loads(request.text)['cities'])

In [6]:
df_cities

                   city  city_id         country   latitude   longitude
0              Abelessa        1         Algeria  22.187777    4.069545
1                 Adrar        2         Algeria  27.875614   -0.290750
2                  Aflu        3         Algeria  34.113883    2.097262
3               Algiers        4         Algeria  36.752887    3.042048
4                Annaba        5         Algeria  36.902859    7.755543
5                 Batna        6         Algeria  35.552991    6.177532
6                Bechar        7         Algeria  31.616097   -2.216623
7                Bejaia        8         Algeria  36.750000    5.066667
8                Biskra        9         Algeria  34.850765    5.728058
9                 Blida       10         Algeria  36.480499    2.833905
10          Constantine       11         Algeria  36.350000    6.600000
11               Djelfa       12         Algeria  34.666667    3.250000
12              Djemila       13         Algeria  36.314416    5.737795
13              El Oued       14         Algeria  33.368309    6.867369
14             Ghardaia       15         Algeria  32.489059    3.678539
15         Hassi Bahbah       16         Algeria  35.072128    3.026104
16            Lakhdaria       17         Algeria  36.562222    3.594444
17                Medea       18         Algeria  36.265132    2.764468
18           Mostaganem       19         Algeria  35.933333    0.083333
19                 Oran       20         Algeria  35.696944   -0.633056
20             Relizane       21         Algeria  35.733333    0.550000
21                Saida       22         Algeria  34.840752    0.149473
22                Setif       23         Algeria  36.190938    5.417857
23             Sidi Ali       24         Algeria  36.100000    0.416667
24            Sidi Amar       25         Algeria  35.096521   -1.836710
25       Sidi Bel Abbes       26         Algeria  35.200000   -0.633333
26               Skikda       27         Algeria  36.866667    6.900000
27          Tamanrasset       28         Algeria  24.098289    3.743509
28              Tazmalt       29         Algeria  36.388118    4.399602
29               Tbessa       30         Algeria  35.407139    8.120864
...                 ...      ...             ...        ...         ...
13454           Tarneit    14131       Australia -37.809168  144.667208
13455           Rožňava    14133        Slovakia  48.656140   20.532384
13456           Borculo    14135     Netherlands  52.113504    6.520360
13457          Semenyih    14136        Malaysia   2.947441  101.845144
13458          Kisvarda    14137         Hungary  48.218115   22.082356
13459       Khorramabad    14142            Iran  33.484221   48.353882
13460   River Falls, WI    14143   United States  44.861356  -92.623808
13461             Utila    14144        Honduras  16.093444  -86.947643
13462            Egkomi    14145          Cyprus  35.159105   33.317748
13463         Torslanda    14147          Sweden  57.723152   11.767668
13464        Acquarossa    14148     Switzerland  46.454583    8.939771
13465              Agno    14149     Switzerland  45.996984    8.899391
13466            Sikkim    14150           India  27.532972   88.512218
13467         Pelhrimov    14151  Czech Republic  49.430621   15.222983
13468        Česká Lípa    14152  Czech Republic  50.678520   14.539699
13469            Morawa    14153       Australia -29.211111  116.008889
13470         Cairo, IL    14154   United States  37.005329  -89.176461
13471   Diamond Bar, CA    14155   United States  34.028623 -117.810337
13472  Stephenville, TX    14156   United States  32.220696  -98.202263
13473      Guardalavaca    14157            Cuba  21.120590  -75.827248
13474          Pembroke    14158           Malta  35.929070   14.475242
13475            Biasca    14159     Switzerland  46.358001    8.970465
13476            Stabio    14160     Switzerland  45.853029    8.936694
13477         Giubiasco    14161     Switzerland  46.172106    9.010393
13478        Pregassona    14162     Switzerland  46.020805    8.975589
13479          Brissago    14163     Switzerland  46.120044    8.711266
13480           Muralto    14164     Switzerland  46.172962    8.805608
13481             Cevio    14166     Switzerland  46.317706    8.602308
13482            Atenas    14167      Costa Rica   9.978494  -84.373839
13483              Moga    14168           India  30.816460   75.171709

[13484 rows x 5 columns]